# Generated by Django 4.2.16 on 2026-05-12 06:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0007_uceproject_ucemilestone_ucetask_ucetimeentry_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("key_encrypted", models.TextField()),
                ("key_prefix", models.CharField(db_index=True, max_length=8)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("client", "Client"),
                            ("viewer", "Viewer"),
                        ],
                        default="viewer",
                        max_length=16,
                    ),
                ),
                ("rate_limit_per_minute", models.PositiveIntegerField(default=100)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("ip_whitelist", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uce_api_keys",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["project__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="ApiKeyUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.CharField(max_length=500)),
                ("http_method", models.CharField(max_length=12)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("response_code", models.PositiveIntegerField(default=200)),
                ("response_time_ms", models.PositiveIntegerField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "api_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_logs",
                        to="api_keys.apikey",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["api_key", "-timestamp"],
                        name="api_keys_ap_api_key_02e4ae_idx",
                    )
                ],
            },
        ),
    ]
